"""Initial migration

Revision ID: 21c199dc3c83
Revises: 
Create Date: 2025-03-27 10:59:48.221873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c199dc3c83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('speciality', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('experience', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fees', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address1', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('about', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doctors_pkey'),
    sa.UniqueConstraint('email', name='doctors_email_key')
    )
    # ### end Alembic commands ###
